---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster: dummy
    nodepool: dummy-fsn1
  name: dummy-fsn1
  namespace: cluster-dummy
spec:
  clusterName: dummy
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        cluster: dummy
        nodepool: dummy-fsn1
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: dummy-worker
      clusterName: dummy
      failureDomain: fsn1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: dummy-worker
      version: v1.33.2

...
