apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "kamaji-cluster.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kamaji-cluster.labels" . | nindent 4 }}
  annotations:
    capi.syself.com/allow-empty-control-plane-address: "true"
spec:
  controlPlaneLoadBalancer:
    enabled: false
  controlPlaneRegions:
    - fsn1
    - nbg1
    - hel1
  hcloudNetwork:
    {{- toYaml .Values.hcloud.network | nindent 4 }}
  hcloudPlacementGroups:
    - name: worker
      type: spread
  hetznerSecretRef:
    name: hetzner
    key:
      hcloudToken: hcloud
      hetznerRobotPassword: robot-password
      hetznerRobotUser: robot-user
  skipCreatingHetznerSecretInWorkloadCluster: true
  sshKeys:
    hcloud:
      {{- range .Values.hcloud.sshKeys }}
      - name: {{ . }}
      {{- end }}
