{{- if .Values.oidc.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cluster-{{ include "kamaji-cluster.clusterName" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kamaji-cluster.labels" . | nindent 4 }}
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      cluster: {{ include "kamaji-cluster.clusterName" . }}
  resources:
    - kind: ConfigMap
      name: cluster-{{ include "kamaji-cluster.clusterName" . }}-oidc
{{- end }}
