apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: {{ include "kamaji-cluster.clusterName" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kamaji-cluster.labels" . | nindent 4 }}
spec:
  dataStoreName: default
  addons:
    coreDNS:
      dnsServiceIPs:
        {{- toYaml .Values.cluster.dns | nindent 8 }}
    konnectivity: {}
    kubeProxy: {}
  {{- if .Values.oidc.enabled }}
  apiServer:
    extraArgs:
      - "--oidc-issuer-url={{ .Values.oidc.issuer }}"
      - "--oidc-client-id={{ .Values.oidc.client }}"
      - "--oidc-username-claim=preferred_username"
      - "--oidc-username-prefix=oidc:"
      - "--oidc-groups-claim=groups"
      - "--oidc-groups-prefix=oidc:"
  {{- end }}
  controllerManager:
    extraArgs:
      - --cloud-provider=external
  scheduler: {}
  deployment:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: kamaji.clastix.io/name
                    operator: In
                    values:
                      - {{ include "kamaji-cluster.clusterName" . }}
              topologyKey: kubernetes.io/hostname
            weight: 100
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
      - ExternalIP
      - InternalIP
      - Hostname
  network:
    {{- if .Values.cluster.sans }}
    certSANs:
      {{- toYaml .Values.cluster.sans | nindent 6 }}
    {{- end }}
    serviceType: {{ .Values.kamaji.serviceType }}
    {{- if eq .Values.kamaji.service "LoadBalancer" }}
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/ttl: "1"
      {{- if .Values.cluster.endpoint }}
      external-dns.alpha.kubernetes.io/hostname: "{{ .Values.cluster.endpoint }}"
      {{- end }}
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
      load-balancer.hetzner.cloud/network-zone: "{{ .Values.kamaji.loadBalancer.zone }}"
      load-balancer.hetzner.cloud/type: "{{ .Values.kamaji.loadBalancer.type }}"
      load-balancer.hetzner.cloud/use-private-ip: "true"
      {{- if .Values.cluster.endpoint }}
      load-balancer.hetzner.cloud/ipv4-rdns: "{{ .Values.cluster.endpoint }}"
      load-balancer.hetzner.cloud/ipv6-rdns: "{{ .Values.cluster.endpoint }}"
      {{- end }}
    {{- end }}
  replicas: {{ .Values.cp.replicas }}
  version: {{ .Values.cluster.version | default (printf "v%s" .Chart.AppVersion) }}
